# Generated by Django 3.2.22 on 2023-10-23 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scan_id', models.CharField(max_length=64, verbose_name='扫描任务的ID')),
                ('child_task_status', models.JSONField(verbose_name='子任务状态')),
                ('status', models.IntegerField(choices=[(0, '正在扫描'), (1, '扫描完成')], default=0, verbose_name='扫描状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_v4', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP地址')),
                ('device_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备名')),
                ('os_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='系统名字')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='系统类型')),
                ('vendor', models.CharField(blank=True, max_length=255, null=True, verbose_name='系统分类')),
                ('os_gen', models.CharField(blank=True, max_length=255, null=True, verbose_name='系统版本')),
                ('os_family', models.CharField(blank=True, max_length=255, null=True, verbose_name='系统家族')),
                ('country_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='国家')),
                ('latitude', models.CharField(blank=True, max_length=32, null=True, verbose_name='纬度')),
                ('longitude', models.CharField(blank=True, max_length=32, null=True, verbose_name='精度')),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mac地址')),
                ('producer', models.CharField(blank=True, max_length=255, null=True, verbose_name='制造商，根据MAC地址查询出来的')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.scantask')),
            ],
        ),
    ]
