# Generated by Django 3.2.22 on 2023-10-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_v4', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP地址')),
                ('device_name', models.CharField(max_length=255, verbose_name='设备名')),
                ('os_name', models.CharField(max_length=255, verbose_name='系统名字')),
                ('type', models.CharField(max_length=255, verbose_name='系统类型')),
                ('vendor', models.CharField(max_length=255, verbose_name='系统分类')),
                ('os_gen', models.CharField(max_length=255, verbose_name='系统版本')),
                ('os_family', models.CharField(max_length=255, verbose_name='系统家族')),
                ('country_name', models.CharField(max_length=255, verbose_name='国家')),
                ('latitude', models.CharField(max_length=32, verbose_name='纬度')),
                ('longitude', models.CharField(max_length=32, verbose_name='精度')),
                ('mac_address', models.CharField(max_length=255, verbose_name='Mac地址')),
                ('producer', models.CharField(max_length=255, verbose_name='制造商，根据MAC地址查询出来的')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
