# Generated by Django 3.2.22 on 2023-10-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CveData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cve_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('cve_url', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.CharField(blank=True, max_length=255, null=True)),
                ('access', models.CharField(blank=True, max_length=255, null=True)),
                ('complexity', models.CharField(blank=True, max_length=255, null=True)),
                ('authentication', models.CharField(blank=True, max_length=255, null=True)),
                ('confidentiality', models.CharField(blank=True, max_length=255, null=True)),
                ('integrity', models.CharField(blank=True, max_length=255, null=True)),
                ('availability', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('snapshot_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cve_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RouterCVE',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cve_id', models.CharField(max_length=255, verbose_name='CVE＿ID')),
                ('cve_desc', models.TextField(verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.scanresult')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.scantask')),
            ],
        ),
    ]
