# Generated by Django 3.2.22 on 2023-10-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_scanresult_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='open_ports',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='开放的端口'),
        ),
    ]
